### ISSUE TITLE
[Suggestion/Idea?] creating a new room

### ISSUE THREAD

**Issue by SylisMC** [Apexal/conexus#5]
Firstly Sorry. im new to github and i cant figure out how to add the proper tag for ideas/requests

But anyways. my idea/request is for you to implement the newish category feature introduced to discord   a while back. this could be extremely powerful for users We could pre set default permissions for text linked channels. if you set category permissions. all channels created in that category inherit the default permissions of that category. this means a user could set ALL new texts chats from conexus to allow file uploading (posting pictures) or allow add new reactions 

also anyone with admin is forced to see ALL of the text channels and such. but if they are in a category by default. we can at least minimize them 

Thanks :)

**Comment by Apexal** [comment]
Great idea! I've been waiting forever to see if the Ruby library I use supports categories yet, but I haven't checked in a while.

I'll check today and get right on it!

**Comment by SylisMC** [comment]
Cool! im glad to know you are still working on the bot (:

**Comment by SylisMC** [comment]
(after thought, even if it created the tab in the same category as the VC that would also keep things clean :D
