### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by daisaku101** [Apexal/conexus#6]
I added the bot, and it shows offline? Is something wrong, no longer supported, or what's up?

**Comment by PhantomNimbi** [comment]
Same issue. It's offline for me too. Is it still in active development? If so is there a Discord support server available to keep up to date with it?

**Comment by Apexal** [comment]
Hello everyone, I dropped working on this when channel categories came out but the discordrb library took forever to support it.

I will revamp the project this week into next week and get it back online, as well as offer a support Discord server.

**Comment by luk701** [comment]
> Hello everyone, I dropped working on this when channel categories came out but the discordrb library took forever to support it.
> 
> I will revamp the project this week into next week and get it back online, as well as offer a support Discord server.

Anything new?

**Comment by Apexal** [comment]
Sorry to everyone who's been waiting on this! University has been keeping me a little too busy lately. I am searching for an open weekend where I can just knock this out.

**Comment by Darkn3ssF4lls** [comment]
> 
> 
> Sorry to everyone who's been waiting on this! University has been keeping me a little too busy lately. I am searching for an open weekend where I can just knock this out.

No problem, I can understand that I am just finishing up my finals myself haha.

**Comment by luk701** [comment]
Could You share with us? @Darkn3ssF4lls?

**Comment by luk701** [comment]
@apexal no problem m8. Thank you.

**Comment by IncarnateNA** [comment]
Any updates on this project? Was really looking forward to the revamp :D

**Comment by Apexal** [comment]
Please see #17
